bazookas_api_framework:
    #  file_upload:
    #    settings:
    #      # probably always equal to media uploads root dir, but you never know, it's a strange world
    #      root_directory: "%root_directory%"
    #      uploads_root_directory: "%uploads_root_directory%"
    #      baseUrl: "%baseUrl%"
    #      uploadRoute: api_v1_upload
    app_copy:
        entity: DemoBundle\Entity\AppCopy
        # required when working with the admin bundle
        details_entity: DemoBundle\Entity\AppCopyDetail
        # optionally provide API specific language constraint (defaults to %requiredlocales%).
        # allowed_locales: nl|fr
    app_settings:
        entity: DemoBundle\Entity\AppSettings
