bazookas_api_framework:
    app_copy:
        entity: App\Entity\App\AppCopy
        details_entity: App\Entity\App\AppCopyDetail
    app_settings:
        entity: App\Entity\App\AppSettings
    app_log:
        entity: App\Entity\App\AppLog
    device:
        entity: App\Entity\App\Device
    file_upload:
        settings:
            uploadRoute: api_v1_upload
