doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            datetime:
                class: Bazookas\CommonBundle\Entity\DoctrineExtensions\Types\UTCDateTimeType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        resolve_target_entities:
            Bazookas\AdminBundle\Entity\Interfaces\CMSUserInterface: Bazookas\AdminBundle\Entity\User\CMSUser
            Bazookas\AdminBundle\Entity\Interfaces\CMSUserGroupInterface: Bazookas\AdminBundle\Entity\User\CMSUserGroup
            Bazookas\APIFrameworkBundle\Entity\Interfaces\AppLogInterface: App\Entity\App\AppLog
            Bazookas\APIFrameworkBundle\Entity\Interfaces\DeviceInterface: App\Entity\App\Device
            Nitro\TokenAuthenticationBundle\Entity\Interfaces\AccessTokenInterface: App\Entity\Auth\AccessToken
            Nitro\TokenAuthenticationBundle\Entity\Interfaces\ClientInterface: App\Entity\Auth\Client
            Symfony\Component\Security\Core\User\UserInterface: App\Entity\User\AppUser
            Nitro\TokenAuthenticationBundle\Entity\Interfaces\RefreshTokenInterface: App\Entity\Auth\RefreshToken
            Nitro\ApiUploadBundle\Entity\Interfaces\ApiFileUploadInterface: App\Entity\Upload\ApiFileUpload
