# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: argon2i

    role_hierarchy:
        ROLE_SUPER_ADMIN:
            #inherited roles
            - ROLE_ADMIN
            #extra roles specific to this role
            - ROLE_ADD_GROUP
            - ROLE_ADD_USER
            - ROLE_MEDIA_ADMIN
            - ROLE_CRON_ADMIN
        ROLE_ADMIN:
            #inherited roles
            #
            #extra roles specific to this role
            - ROLE_CMS_USER
            - ROLE_ADD_USER
            - ROLE_COPY_MANAGER
            - ROLE_MEDIA_ADMIN

    providers:
        users:
            entity:
                class: Bazookas\AdminBundle\Entity\Interfaces\CMSUserInterface

    firewalls:
        #Default Project configuration
        insecure:
            pattern:  ^/(media|cron|(api/doc)|_(profiler|wdt)|css|images|js)
            security: false

        #Default CMS configuration
        admin:
            pattern: ^\/(nl|en)+\/admin
            guard:
                authenticators:
                    - Bazookas\AdminBundle\Security\LoginFormAuthenticator
            anonymous:    true
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path:     /
                domain:   ~
            # TODO fix this
            #            switch_user:
            #                provider: ~
            #                parameter: _switch_user
            #                role: ROLE_ALLOWED_TO_SWITCH
            logout_on_user_change: true

        #Default Project configuration
        main:
            anonymous: ~
            logout_on_user_change: true

    # any login or register paths can be visited anonymously
    # all other admin paths should be secured
    access_control:
        # #for a cms + website project, use the settings below:
        - { path: ^\/(nl|en)+\/admin\/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^\/(nl|en)+\/admin\/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^\/(nl|en)+\/admin\/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^\/(nl|en)+\/admin((\/)*.)*$, role: ROLE_CMS_USER }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
