twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - '@BazookasAdmin/Form/fields.html.twig'
    globals:
        locales: "%locales%"
        showAdminMenu: true
        googleClientID: "%google_api.client_id%"
