# ---------------------------------------------------
#                       App Copy & Settings
# ---------------------------------------------------
bazookas_api_framework_app_copy_admin:
    path: /app_copy/{_action}/{_id}
    defaults:
        _controller: Nitro\AppCopyBundle\Controller\Admin\AppCopyAdminController::indexAction
        _locale: "%locale%"
        _action: ~
        _id: ~
    requirements:
        _locale: "%require_admin_locales%"
        _id: .+

bazookas_api_framework_app_settings_admin:
    path: /app_settings/{_action}/{_id}
    defaults:
        _controller: Nitro\AppSettingsBundle\Controller\Admin\AppSettingsAdminController::indexAction
        _locale: "%locale%"
        _action: ~
        _id: ~
    requirements:
        _locale: "%require_admin_locales%"
        _id: .+

# ---------------------------------------------------
#                       Devices & Logs
# ---------------------------------------------------
bazookas_api_framework_app_log_admin:
    path: /app_logs/{_action}/{_id}
    defaults:
        _controller: Bazookas\APIFrameworkBundle\Controller\Admin\AppLogAdminController::indexAction
        _locale: "%locale%"
        _action: ~
        _id: ~
    requirements:
        _locale: "%require_admin_locales%"
        _id: .+

bazookas_api_framework_device_admin:
    path: /devices/{_action}/{_id}
    defaults:
        _controller: Bazookas\APIFrameworkBundle\Controller\Admin\DeviceAdminController::indexAction
        _locale: "%locale%"
        _action: ~
        _id: ~
    requirements:
        _locale: "%require_admin_locales%"
        _id: .+

# ---------------------------------------------------
#                          Fact
# ---------------------------------------------------
admin_facts:
    path: /facts/{_action}/{_id}
    defaults:
        _controller: App\Controller\Admin\Fact\FactAdminController:indexAction
        _action: ~
        _id: ~
    requirements:
        _locale: "%require_admin_locales%"
        _id: .+
