demo_example_post:
  path: /examples
  defaults:
    _controller: DemoBundle:api\Example:post
  methods: [POST]

demo_example_get:
  path: /examples
  defaults:
    _controller: DemoBundle:api\Example:get
  methods: [GET]

demo_example_publish:
  path: /examples/{_id}/publish
  defaults:
    _controller: DemoBundle:api\Example:publish
  methods: [PUT]

demo_file_upload:
  path: /upload/{_hash}/{_index}
  defaults:
    _controller: BazookasAPIFrameworkBundle:FileUpload:upload
  methods:
    - POST
    - PUT

api_v1_get_settings:
  path: /settings
  methods: [GET]
  defaults:
    _controller: BazookasAPIFrameworkBundle:AppSettings:get

api_v1_get_copy:
  path: /translations
  methods: [GET]
  defaults:
    _controller: BazookasAPIFrameworkBundle:AppCopy:get

