bazookas_admin:
  notifications:
    notificationEntities:
      CMSNotification: DemoBundle\Entity\CMSNotification
      EmailNotification: DemoBundle\Entity\EmailNotification

twig:
    globals:
      enableCMSNotifications: true
