#mutli language api:
api_v1:
  resource: "@DemoBundle/Resources/config/api_routing.yml"
  prefix:   /api/v1.0/{_locale}
  defaults:
    _locale: "%locale%"
  requirements:
    _locale: "%require_admin_locales%"

#mutli language api:
demo_admin:
  resource: "@DemoBundle/Resources/config/admin_routing.yml"
  prefix:   /{_locale}/admin
  defaults:
    _locale: "%locale%"
  requirements:
    _locale: "%require_admin_locales%"
