demo_example_admin:
    path:     /{_locale}/admin/example/{_action}/{_id}
    defaults:
      _controller: DemoBundle:ExampleAdmin:index
      _action: ~
      _id: ~


# API ROUTES
demo_example_post:
  path: /api/{_locale}/examples
  defaults:
    _controller: DemoBundle:api\Example:post
    _locale: %locale%
  requirements:
    _locale: %requiredlocales%
  methods: [POST]

demo_example_get:
  path: /api/{_locale}/examples
  defaults:
    _controller: DemoBundle:api\Example:get
    _locale: %locale%
  requirements:
    _locale: %requiredlocales%
  methods: [GET]

demo_example_publish:
  path: /api/{_locale}/examples/{_id}/publish
  defaults:
    _controller: DemoBundle:api\Example:publish
    _locale: %locale%
  requirements:
    _locale: %requiredlocales%
  methods: [PUT]

demo_temp_admin:
    path:     /{_locale}/admin/temp/{_action}/{_id}
    defaults:
      _controller: DemoBundle:TempAdmin:index
      _action: ~
      _id: ~
