services:
#    demo.example:
#        class: DemoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  demo.example.service:
    class: DemoBundle\Services\ExampleService
    arguments:
      - "@BazookasAPIFrameworkBundle.upload.fileUploadService"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: APIFrameworkBundle.Data.DataService }

  admin.notifications.exampleNotificationSubscriber:
    class: DemoBundle\EventListener\ExampleNotificationSubscriber
    arguments:
      - "@service_container"
      - "@router"
    tags:
      - { name: doctrine.event_subscriber, connection: default }


# -----------------------------------------------------------------------------
#                             DATA
# -----------------------------------------------------------------------------
  DemoBundle.Services.DashboardDataService:
    class: DemoBundle\Services\Data\DashboardDataService
    arguments:
      - "@doctrine.orm.entity_manager"
    lazy:  true
