services:
#    demo.example:
#        class: DemoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  demo.example.service:
    class: DemoBundle\Services\ExampleService
    arguments:
      - "@BazookasAPIFrameworkBundle.upload.fileUploadService"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: APIFrameworkBundle.Data.DataService }

  demo.example.import_service:
    class: DemoBundle\Services\ExampleImportService
    arguments:
      - "@doctrine.orm.entity_manager"
      - '%kernel.root_dir%/../'


# -----------------------------------------------------------------------------
#                             DATA
# -----------------------------------------------------------------------------
  DemoBundle.Services.DashboardDataService:
    class: DemoBundle\Services\Data\DashboardDataService
    arguments:
      - "@doctrine.orm.entity_manager"
    lazy:  true
