services:
  DemoBundle\Services\ExampleService:
    alias: demo_bundle.services.example_service

  DemoBundle\Services\ExampleImportService:
    arguments:
      - "@doctrine.orm.entity_manager"
      - '%kernel.root_dir%/../'


# -----------------------------------------------------------------------------
#                             DATA
# -----------------------------------------------------------------------------
  DemoBundle.Services.DashboardDataService:
    class: DemoBundle\Services\Data\DashboardDataService
    arguments:
      - "@doctrine.orm.entity_manager"
    lazy:  true

  demo_bundle.services.example_service:
    class: DemoBundle\Services\ExampleService
    arguments:
      - "@bazookas.api_framework.upload.file_upload_service"
      - "@doctrine.orm.entity_manager"
    tags:
          - { name: APIFrameworkBundle.Data.DataService }
