services:
#    demo.example:
#        class: DemoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  demo.example.service:
    class: DemoBundle\Services\ExampleService
    arguments:
      - "@demo.example.repository"
      - "@BazookasAPIFrameworkBundle.upload.fileUploadService"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: APIFrameworkBundle.Data.DataService }

  demo.example.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
        - DemoBundle\Entity\Example

# -----------------------------------------------------------------------------
#                             DATA
# -----------------------------------------------------------------------------
  DemoBundle.Services.DashboardDataService:
    class: DemoBundle\Services\Data\DashboardDataService
    arguments:
      - "@doctrine.orm.entity_manager"
    lazy:  true
