<?php

namespace DemoBundle\Repository;
use Bazookas\AdminBundle\Repository\Base\BaseRepository;
use DemoBundle\Entity\Example;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpFoundation\ParameterBag;

/**
 * ExampleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExampleRepository extends BaseRepository
{
  public function getEntityClass(): string
  {
    return Example::class;
  }

  public function create(ParameterBag $parameterBag) {
    $result = new Example();

    dump($parameterBag);
    exit();


    return $result;
  }

  public function getPagedList($page = 0, $resultsPerPage = 10) {
    $qb = $this
      ->createQueryBuilder('example');

    $query = $qb
      ->select('
        partial example.{id, title, created, modified},
        partial image.{id, title, url},
        partial multipleImages.{id, title, url}
      ')

      ->leftJoin('example.singleImage', 'image')
      ->leftJoin('example.multipleImages', 'multipleImages')

      ->setFirstResult($page * $resultsPerPage)
      ->setMaxResults($resultsPerPage)
      // ->getQuery()
      // ->getArrayResult()
    ;

    $paginator = new Paginator($query);

    return array(
      'data' => $paginator->getQuery()->getArrayResult(),
      'pages' => ceil($paginator->count() / $resultsPerPage),
    );
  }
}
