imports:
  - { resource: config_dev.yml }

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
    name: MOCKSESSID
  profiler:
    collect: false

web_profiler:
  toolbar: false
  intercept_redirects: false

swiftmailer:
  disable_delivery: true

doctrine:
  dbal:
    driver:   pdo_mysql
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%_test"
    user:     "%database_user%"
    password: "%database_password%"
    #        charset: utf8mb4
    charset:  UTF8
    #this causes issues with fos user bundle
    #        default_table_options:
    #            charset: utf8mb4
    #            collate: utf8mb4_unicode_ci
    types:
      datetime: Bazookas\CommonBundle\Entity\DoctrineExtensions\Types\UTCDateTimeType

liip_functional_test:
  cache_sqlite_db: true
