# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  encoders:
    #Default CMS configuration
    Bazookas\AdminBundle\Entity\Interfaces\CMSUserInterface:
      algorithm: bcrypt
      cost: 13

    #Default Project configuration
    Bazookas\CommonBundle\Entity\Base\BaseUser:
      algorithm: bcrypt
      cost: 13

  role_hierarchy:
    ROLE_SUPER_ADMIN:
      #inherit roles
      - ROLE_ADMIN
      #extra roles specific to this role
      - ROLE_ADD_GROUP
      - ROLE_ADD_USER
      - ROLE_MEDIA_ADMIN
      - ROLE_CRON_ADMIN
    ROLE_ADMIN:
      #inherit roles
      #
      #extra roles specific to this role
      - ROLE_CMS_USER
      - ROLE_ADD_USER
      - ROLE_COPY_MANAGER
      - ROLE_MEDIA_ADMIN

  # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
  providers:
    base_user_provider:
      id: api.user_provider.base_user_provider

  firewalls:
    #Default Project configuration
    insecure:
      pattern:  ^/(media|cron|(api/doc)|_(profiler|wdt)|css|images|js)
      security: false

    #Default API configuration
    token:
      pattern:    ^/(api/v1.0/token)|(api/oauth/v2/token)
      security:   false
    api:
      pattern:    ^/api
      fos_oauth:  true
      stateless:  true
      provider: base_user_provider

    #Default CMS configuration
    admin:
      pattern: ^\/(nl|en)+\/admin
      form_login:
        login_path: admin_login
        check_path: admin_login
        default_target_path: bazookas_admin_homepage
      logout:
        path:   admin_logout
        target: admin_login
      anonymous:    true
      remember_me:
        secret: "%secret%"
        lifetime: 604800
        path:     /
        domain:   ~
      switch_user:
        provider: ~
        parameter: _switch_user
        role: ROLE_ALLOWED_TO_SWITCH
      logout_on_user_change: true

    #Default Project configuration
    main:
      anonymous: ~
      logout_on_user_change: true

  # any login or register paths can be visited anonymously
  # all other admin paths should be secured
  access_control:
    #for a cms only project, use the settings below:
    # - { path: ^\/(nl|en)+\/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^\/(nl|en)+\/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^\/(nl|en)+\/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^\/(nl|en)+\?/$, role: [ROLE_CMS_USER, IS_AUTHENTICATED_ANONYMOUSLY] }
    # - { path: ^\/(nl|en)+\/, role: ROLE_CMS_USER }
    # - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

    # #for a cms + website project, use the settings below:
    - { path: ^\/(nl|en)+\/admin\/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^\/(nl|en)+\/admin\/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^\/(nl|en)+\/admin\/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^\/(nl|en)+\/admin((\/)*.)*$, role: ROLE_CMS_USER }
    - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
