services:
# -----------------------------------------------------------------------------
#                             Security
# -----------------------------------------------------------------------------
  #NOTE: an example of how to define a user provider service
  api.user_provider.base_user_provider:
    class: Bazookas\SecurityBundle\UserProviders\BaseUserProvider
    arguments:
      - "@doctrine.orm.entity_manager"
      - { entity: 'APIBundle\Entity\AppUser' }

