# prefix all admin routes with /admin/
# this way we can provide custom admin URLs per project
bazookas_admin:
    resource: "@BazookasAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    defaults:
        _locale: "%locale%"
    requirements:
        _locale: "%require_admin_locales%"

bazookas_cron:
    resource: "@BazookasCronBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    defaults:
        _locale: "%locale%"
    requirements:
        _locale: "%require_admin_locales%"

bazookas_media:
    resource: "@BazookasMediaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    defaults:
        _locale: "%locale%"
    requirements:
        _locale: "%require_admin_locales%"

api_framework:
    resource: "@BazookasAPIFrameworkBundle/Resources/config/routing.yml"
    prefix:   /
