api_v1_token:
    path: /token
    methods: [POST]
    defaults:
      _controller: APIBundle:v1_0\Auth:token

api_v1_upload:
  path: files/upload/{_hash}/{_index}
  defaults:
    _controller: BazookasAPIFrameworkBundle:FileUpload:upload
    _locale: "%locale%"
  requirements:
    _locale: "%requiredlocales%"
  methods: [POST]

api_v1_example:
  path: /example/{_id}
  methods: [GET, DELETE, POST, PUT, PATCH]
  defaults:
    _controller: APIBundle:v1_0\Example:handleRequest
    _id: ~

api_v1_product:
  path: /product/{_id}
  methods: [GET, DELETE, POST, PUT, PATCH]
  defaults:
    _controller: APIBundle:v1_0\Product:handleRequest
    _id: ~
